### ISSUE TITLE
Pay dosent work

### ISSUE THREAD

**Issue by obamajoepoop** [Moutamid/CashAppReplica#1]
why dosent the pay button work when i put a name? when i put a name too nothing pops up?

**Comment by Moutamid** [comment]
You need to add an amount also

**Comment by obamajoepoop** [comment]
> You need to add an amount also

i did

**Comment by Moutamid** [comment]
Can you connect with me on telegram or WhatsApp?
Mine is +971567257157

**Comment by obamajoepoop** [comment]
> 971567257157

yes

**Comment by obamajoepoop** [comment]
ill do whatsapp

**Comment by obamajoepoop** [comment]
nevermind telegram

**Comment by obamajoepoop** [comment]
just messaged you

**Comment by obamajoepoop** [comment]
on telegram

**Comment by obamajoepoop** [comment]
i just messaged you
